name: Create Release

on:
  push:
    tags:
      - "v*"

permissions:
    contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
  
  release:
    needs: build
    runs-on: windows-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: win-release-artifacts
        github-token: ${{ github.token }}
        run-id: ${{ jobs.build.outputs.run_id }}

    - name: List files
      run: ls -R .

    - name: Package
      shell: bash
      run: |
        7z a -tzip "DurangoInterop_${{github.ref_name}}.zip" "*"

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: "DurangoInterop_${{github.ref_name}}.zip"
        make_latest: true
        generate_release_notes: true
        fail_on_unmatched_files: true
